[profile.default]
src = 'contracts'
out = 'out'
script = "scripts"
libs = ["node_modules", "lib"]
build_info = true
extra_output = ["storageLayout"]
ffi = true
ast = true
fs_permissions = [{ access = "read", path = "./out" }]
